[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "description"
[tool.poetry.dependencies]
fake-useragent = "==0.1.11"
prompt-toolkit = "==1.0.14"
pyinquirer = "==1.0.3"
python = "^3.8"
rsa = "==4.0"
tqdm = "==4.36.1"
<<<<<<< HEAD
lxml = "^4.6.4"
requests = "^2.26.0"
=======
cachetools = "^4.2.4"
>>>>>>> b95d5153760869c2cb77735c1c23e289ec17c36d
